//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Core.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; parameter cannot be null or empty..
        /// </summary>
        internal static string CannotBeNullOrEmpy {
            get {
                return ResourceManager.GetString("CannotBeNullOrEmpy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot desirialize &apos;{0}&apos; file into &apos;{1}&apos; object. See inner exception for more details..
        /// </summary>
        internal static string CannotDeserializeFile {
            get {
                return ResourceManager.GetString("CannotDeserializeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;body&gt;&lt;div style=&quot;font-family: Verdana&quot;&gt;{{Message}}&lt;/div&gt;&lt;/body&gt;&lt;html&gt;.
        /// </summary>
        internal static string EmailNotificationTemplate {
            get {
                return ResourceManager.GetString("EmailNotificationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have exceeded the maximum number of failed login attempts. ({0} attempts for {1} minutes. Time left: {2}).
        /// </summary>
        internal static string ExceededFailedLoginAttempts {
            get {
                return ResourceManager.GetString("ExceededFailedLoginAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; has wrong formatting..
        /// </summary>
        internal static string FileIsInWrongFormatting {
            get {
                return ResourceManager.GetString("FileIsInWrongFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find &apos;{0}&apos; file referenced in &apos;{1}&apos;..
        /// </summary>
        internal static string FileReferenceDoesNotExist {
            get {
                return ResourceManager.GetString("FileReferenceDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Froum with urlName &apos;{0}&apos; was not found..
        /// </summary>
        internal static string ForumNotFound {
            get {
                return ResourceManager.GetString("ForumNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriber with this email address &apos;{0}&apos; already exists..
        /// </summary>
        internal static string SubscriberExists {
            get {
                return ResourceManager.GetString("SubscriberExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with username &apos;{0}&apos; was not found..
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong name or email address. Make sure you spelt it correctly. It should be in the following format: &quot;Your Name, email@address.com&quot;.
        /// </summary>
        internal static string WrongSubscriberEmail {
            get {
                return ResourceManager.GetString("WrongSubscriberEmail", resourceCulture);
            }
        }
    }
}
